# Generated by ChatGPT on 2026-02-18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0004_alter_category_category_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='duplicate_of',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='duplicates',
                to='gallery.photo',
            ),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(
                fields=('user', 'file_hash'),
                condition=Q(file_hash__isnull=False, is_deleted=False),
                name='uniq_user_filehash_active',
            ),
        ),
    ]