# Generated by ChatGPT on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0005_photo_duplicate_of_and_unique_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "대기"),
                    ("PROCESSING", "처리중"),
                    ("DONE", "완료"),
                    ("FAILED", "실패"),
                ],
                default="PENDING",
                max_length=20,
                db_index=True,
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="processing_error",
            field=models.TextField(blank=True, null=True),
        ),
    ]