# Generated by Django 4.2.17 on 2026-02-02 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_email', models.EmailField(max_length=254)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_uri', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('scopes', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_credential', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'google_credentials',
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('source', models.CharField(default='GOOGLE', max_length=20)),
                ('folder_id', models.CharField(blank=True, max_length=255, null=True)),
                ('total_count', models.IntegerField(default=0)),
                ('done_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='import_jobs_user_id_2d2855_idx')],
            },
        ),
    ]
