# Generated by Django 4.2.17 on 2026-02-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='picker_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('PICKING', 'Picking'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='QUEUED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['picker_session_id'], name='import_jobs_picker__ed9de7_idx'),
        ),
    ]
